<div class="span2">
    <div class="well side-nav">
        <ul class="nav nav-list" id="navList">
            <?php if (in_array(1, $permssionList)) { ?>
                <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'hotel'); ?>
                </span>
                    <ul class="nav nav-list nav-li-list hide">
                        <li><a href="/hotel/info"><?php echo Enum_Lang::getPageText('nav', 'hotelInfo'); ?></a></li>
                        <li><a href="/hotel/floor"><?php echo Enum_Lang::getPageText('nav', 'hotelFloor'); ?></a></li>
                        <li><a href="/hotel/facilities"><?php echo Enum_Lang::getPageText('nav', 'hotelFacilities'); ?></a></li>
                        <li><a href="/hotel/traffic"><?php echo Enum_Lang::getPageText('nav', 'hotelTraffic'); ?></a></li>
                        <li><a href="/hotel/panoramic"><?php echo Enum_Lang::getPageText('nav', 'hotelPanoramic'); ?></a></li>
                        <li><a href="/hotel/pic"><?php echo Enum_Lang::getPageText('nav', 'hotelPic'); ?></a></li>
                        <li><a href="/hotel/title"><?php echo Enum_Lang::getPageText('nav', 'hotelTitle'); ?></a></li>
                    </ul>
                </li>
            <?php } ?>
            <?php if (in_array(2, $permssionList)) { ?>
                <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'activity'); ?>
                </span>
                    <ul class="nav nav-list nav-li-list hide">
                        <li><a href="/activity/tag"><?php echo Enum_Lang::getPageText('nav', 'activityTag'); ?></a></li>
                        <li><a href="/activity/list"><?php echo Enum_Lang::getPageText('nav', 'activityList'); ?></a></li>
                        <li><a href="/activity/order"><?php echo Enum_Lang::getPageText('nav', 'activityOrder'); ?></a></li>
                    </ul>
                </li>
            <?php } ?>
            <?php if (in_array(3, $permssionList)) { ?>
                <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'life'); ?>
                </span>
                    <ul class="nav nav-list nav-li-list hide">
                        <li><a href="/ascott/typeList"><?php echo Enum_Lang::getPageText('nav', 'lifeType'); ?></a></li>
                        <li><a href="/ascott/list"><?php echo Enum_Lang::getPageText('nav', 'lifeList'); ?></a></li>
                    </ul>
                </li>
            <?php } ?>
            <?php if (in_array(4, $permssionList)) { ?>
                <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'poi'); ?>
                </span>
                    <ul class="nav nav-list nav-li-list hide">
                        <li><a href="/poi/tag"><?php echo Enum_Lang::getPageText('nav', 'poiTag'); ?></a></li>
                        <li><a href="/poi/typeList"><?php echo Enum_Lang::getPageText('nav', 'poiType'); ?></a></li>
                        <li><a href="/poi/list"><?php echo Enum_Lang::getPageText('nav', 'poiList'); ?></a></li>
                    </ul>
                </li>
            <?php } ?>
            <?php if (in_array(5, $permssionList)) { ?>
                <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'promotion'); ?>
                </span>
                    <ul class="nav nav-list nav-li-list hide">
                        <li><a href="/promotion/tagList"><?php echo Enum_Lang::getPageText('nav', 'promotionTag'); ?></a></li>
                        <li><a href="/promotion/list"><?php echo Enum_Lang::getPageText('nav', 'promotionList'); ?></a></li>
                    </ul>
                </li>
            <?php } ?>
            <?php if (in_array(6, $permssionList)) { ?>
                <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'room'); ?>
                </span>
                    <ul class="nav nav-list nav-li-list hide">
                        <li><a href="/room/roomType"><?php echo Enum_Lang::getPageText('nav', 'roomType'); ?></a></li>
                        <li><a href="/room/roomRes"><?php echo Enum_Lang::getPageText('nav', 'roomRes'); ?></a></li>
                        <li><a href="/room/roomList"><?php echo Enum_Lang::getPageText('nav', 'ROOMLIST'); ?></a></li>
                        <li><a href="/room/billList"><?php echo Enum_Lang::getPageText('nav', 'billList'); ?></a></li>
                    </ul>
                </li>
            <?php } ?>
            <?php if (in_array(7, $permssionList)) { ?>
                <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'shopping'); ?>
                </span>
                    <ul class="nav nav-list nav-li-list hide">
                        <li><a href="/shopping/tag"><?php echo Enum_Lang::getPageText('nav', 'shoppingTag'); ?></a></li>
                        <li><a href="/shopping/list"><?php echo Enum_Lang::getPageText('nav', 'shoppingList'); ?></a></li>
                        <li><a href="/shopping/order"><?php echo Enum_Lang::getPageText('nav', 'shoppingOrder'); ?></a></li>
                    </ul>
                </li>
            <?php } ?>
            <?php if (in_array(8, $permssionList)) { ?>
                <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'showing'); ?>
                </span>
                    <ul class="nav nav-list nav-li-list hide">
                        <li><a href="/showing/order"><?php echo Enum_Lang::getPageText('nav', 'showingOrder'); ?></a></li>
                    </ul>
                </li>
            <?php } ?>
            <?php if (in_array(9, $permssionList)) { ?>
                <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'tel'); ?>
                </span>
                    <ul class="nav nav-list nav-li-list hide">
                        <li><a href="/tel/telType"><?php echo Enum_Lang::getPageText('nav', 'telType'); ?></a></li>
                        <li><a href="/tel/list"><?php echo Enum_Lang::getPageText('nav', 'telList'); ?></a></li>
                    </ul>
                </li>
            <?php } ?>
            <?php if (in_array(10, $permssionList)) { ?>
                <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'news'); ?>
                </span>
                    <ul class="nav nav-list nav-li-list hide">
                        <li><a href="/news/tagList"><?php echo Enum_Lang::getPageText('nav', 'newsTag'); ?></a></li>
                        <li><a href="/news/list"><?php echo Enum_Lang::getPageText('nav', 'newsList'); ?></a></li>
                    </ul>
                </li>
            <?php } ?>
            <?php if (in_array(11, $permssionList)) { ?>
                <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'notic'); ?>
                </span>
                    <ul class="nav nav-list nav-li-list hide">
                        <li><a href="/notic/tagList"><?php echo Enum_Lang::getPageText('nav', 'noticTag'); ?></a></li>
                        <li><a href="/notic/list"><?php echo Enum_Lang::getPageText('nav', 'noticList'); ?></a></li>
                    </ul>
                </li>
            <?php } ?>
            <?php if (in_array(12, $permssionList)) { ?>
                <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'feedback'); ?>
                </span>
                    <ul class="nav nav-list nav-li-list hide">
                        <li><a href="/feedback/list"><?php echo Enum_Lang::getPageText('nav', 'feedbackList'); ?></a></li>
                        <li><a href="/feedback/question"><?php echo Enum_Lang::getPageText('nav', 'feedbackQuestion'); ?></a></li>
                        <li><a href="/feedback/result"><?php echo Enum_Lang::getPageText('nav', 'feedbackResult'); ?></a></li>
                    </ul>
                </li>
            <?php } ?>
            <?php if (in_array(13, $permssionList)) { ?>
                <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'app'); ?>
                </span>
                    <ul class="nav nav-list nav-li-list hide">
                        <li><a href="/app/roomPush"><?php echo Enum_Lang::getPageText('nav', 'appRoomPush'); ?></a></li>
                        <li><a href="/app/push"><?php echo Enum_Lang::getPageText('nav', 'appPush'); ?></a></li>
                        <li><a href="/app/shortcut"><?php echo Enum_Lang::getPageText('nav', 'appShortcut'); ?></a></li>
                        <li><a href="/app/share"><?php echo Enum_Lang::getPageText('nav', 'appShare'); ?></a></li>
                        <li><a href="/app/rss"><?php echo Enum_Lang::getPageText('nav', 'appRss'); ?></a></li>
                        <li><a href="/app/staff"><?php echo Enum_Lang::getPageText('nav', 'appStaff'); ?></a></li>
                    </ul>
                </li>
            <?php } ?>
            <?php if (in_array(14, $permssionList)) { ?>
                <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'comment'); ?>
                </span>
                    <ul class="nav nav-list nav-li-list hide">
                        <li><a href="/comment/list"><?php echo Enum_Lang::getPageText('nav', 'commentList'); ?></a></li>
                    </ul>
                </li>
            <?php } ?>

            <?php if (in_array(15, $permssionList)) { ?>
                <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'service'); ?>
                </span>
                    <ul class="nav nav-list nav-li-list hide">
                    <?php
                        foreach ($taskPermissionList as $taskPermission){
                            $li = sprintf('<li><a href="%s">%s</a></li>', $taskPermission['url'], $taskPermission['name_lang1']);
                            echo $li;
                        }
                    ?>
                    </ul>
                </li>
            <?php } ?>

            <?php if (in_array(16, $permssionList)) { ?>
                <li class="nav-header">
                <span class="nav-header-open">
                    <i class="icon-plus icon-plus-opacity pull-right"></i><?php echo Enum_Lang::getPageText('nav', 'sign'); ?>
                </span>
                    <ul class="nav nav-list nav-li-list hide">
                        <li><a href="/sign/category"><?php echo Enum_Lang::getPageText('nav', 'signCategory'); ?></a>
                        </li>
                        <li><a href="/sign/item"><?php echo Enum_Lang::getPageText('nav', 'signItem'); ?></a></li>
                    </ul>
                </li>
            <?php } ?>
        </ul>
    </div>
</div>
<script type="text/javascript">
    var log = console.log.bind(console) || alert;
    $(function () {
        var pathname = window.location.pathname;
        var defaultSelected = 0;
        if (!pathname) {
            defaultSelected = 1;
        }

        $('.nav-li-list a').each(function (i, item) {
            var item = $(item);
            if (defaultSelected) {
                if (i == 0) {
                    item.parent().addClass('active').parent('ul').removeClass('hide');
                    return;
                }
            } else {
                if (item.attr('href') == pathname) {
                    item.parent().addClass('active').parent('ul').removeClass('hide').prev().children('i').removeClass('icon-plus').addClass('icon-minus');
                    return;
                }
            }
        });

        $('.nav-header-open').on('click', function () {
            var T = $(this);
            var flag = T.next('.nav-li-list').toggle().css('display');
            if (flag == 'block') {
                T.find('i').removeClass('icon-plus').addClass('icon-minus');
                var item = T.parents('ul').siblings().find('.nav-li-list').hide();
            } else {
                T.find('i').removeClass('icon-minus').addClass('icon-plus');
            }
            T.parents('ul').siblings().find('i').removeClass('icon-minus').addClass('icon-plus');
        })
    });
</script>
