<div class="modal hide fade yulong" id="editor" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"><?php echo Enum_Lang::getPageText('group', 'editTitle'); ?></h4>
            </div>
            <div class="modal-body" id="detailBody" mf="modalfix">
                <form class="form-horizontal" id="listEditor">
                    <input type="hidden" id="edit_id" value="0">

                    <?php foreach ($hotelLanguageList as $index => $language) { ?>
                        <?php $filedTitle = Enum_Lang::getPageText('poi', 'title') . '（' . Enum_Lang::getPageText('language', $language) . '）'; ?>
                        <?php $filedIndex = $index + 1; ?>
                        <div class="control-group" op="editFiled">
                            <label class="control-label" for="edit_titleLang<?php echo $filedIndex; ?>"><?php echo $filedTitle; ?>：</label>
                            <div class="controls">
                                <input type="text" id="edit_titleLang<?php echo $filedIndex; ?>" placeholder="<?php echo $filedTitle; ?>" class="span3" data-title="<?php echo $filedTitle; ?>">
                            </div>
                        </div>
                    <?php } ?>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_tagid"><?php echo Enum_Lang::getPageText('poi', 'tagTitle'); ?>：</label>
                        <div class="controls">
                            <select id="edit_tagid" data-title="标签">
                                <?php foreach ($tagList as $tag) { ?>
                                    <option value="<?php echo $tag['id']; ?>"><?php echo $tag['title_lang1']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_status"><?php echo Enum_Lang::getPageText('poi', 'status'); ?>：</label>
                        <div class="controls">
                            <select id="edit_status" data-title="状态">
                                <option value="0"><?php echo Enum_Lang::getPageText('poi', 'disable'); ?></option>
                                <option value="1"><?php echo Enum_Lang::getPageText('poi', 'enable'); ?></option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" id="saveListData"
                        data-loading-text="<?php echo Enum_Lang::getPageText('system', 'saveing'); ?>"><?php echo Enum_Lang::getPageText('system', 'save'); ?></button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" id='closeEditor'><?php echo Enum_Lang::getPageText('system', 'close'); ?></button>
            </div>
        </div>
    </div>
</div>
