<!DOCTYPE HTML>
<html>
<head>
<?php include($webConfig['layoutPath'].'/common/meta.phtml')?>
</head>
<body>
<?php include($webConfig['layoutPath'].'/common/header.phtml')?>
<div class="container container-main" >
    <div class="row-fluid">
    <?php include($webConfig['layoutPath'].'/common/nav.phtml')?>
    </div>
</div>
<div class="container container-footer">
	<a href='ICP_file_link' target="_blank">京ICP备</a>
</div>
</body>
</html>