<div class="modal hide fade yulong" id="editor" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
     mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title"
                    id="myModalLabel"><?php echo Enum_Lang::getPageText('shopping', 'editTagTitle'); ?></h4>
            </div>
            <div class="modal-body" id="detailBody" mf="modalfix">
                <form class="form-horizontal" id="listEditor">
                    <input type="hidden" id="edit_id" value="0">
                    <div class="control-group" op="editFiled">
                        <label class="control-label"
                               for="edit_position"><?php echo Enum_Lang::getPageText('robot', 'position'); ?>：</label>
                        <div class="controls">
                            <input type="text" id="edit_position"
                                   placeholder="<?php echo Enum_Lang::getPageText('robot', 'position'); ?>"
                                   class="span3"
                                   data-title="<?php echo Enum_Lang::getPageText('robot', 'position'); ?>">
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label"
                               for="edit_robotposition"><?php echo Enum_Lang::getPageText('robot', 'robotPosition'); ?>
                            ：</label>
                        <div class="controls">
                            <input type="text" id="edit_robotposition"
                                   placeholder="<?php echo Enum_Lang::getPageText('robot', 'robotPosition'); ?>"
                                   class="span3"
                                   data-title="<?php echo Enum_Lang::getPageText('robot', 'robotPosition'); ?>">
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label"
                               for="edit_positiontype"><?php echo Enum_Lang::getPageText('robot', 'positionType'); ?>
                            ：</label>
                        <div class="controls">
                            <select id="edit_positiontype">
                                <?php foreach ($positionTypeList as $key => $name) { ?>
                                    <option value="<?php echo $key; ?>" class="span3"><?php echo $name; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" id="saveListData"
                        data-loading-text="<?php echo Enum_Lang::getPageText('system', 'saveing'); ?>"><?php echo Enum_Lang::getPageText('system', 'save'); ?></button>
                <button type="button" class="btn btn-primary" data-dismiss="modal"
                        id='closeEditor'><?php echo Enum_Lang::getPageText('system', 'close'); ?></button>
            </div>
        </div>
    </div>
</div>
