<div class="modal hide fade yulong" id="processEditor" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
     mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title"
                    id="myModalLabel"><?php echo Enum_Lang::getPageText('service', 'TaskOrderProcess'); ?></h4>
            </div>
            <div class="modal-body" id="detailBody" mf="modalfix">
                <form class="form-horizontal" id="processListEditor">
                    <input type="hidden" id="edit_id" value="0">
                    <div class="control-group" op="editFiled">
                        <label class="control-label"
                               for="edit_adminid"><?php echo Enum_Lang::getPageText('service', 'staff'); ?>：</label>
                        <div class="controls">
                            <select id="edit_adminid"
                                    data-title="<?php echo Enum_Lang::getPageText('service', 'staff'); ?>">
                                <option value=""></option>
                                <?php
                                foreach ($staffList as $staff) {
                                    $option = sprintf("<option value='%s'>%s</option>", $staff['id'], $staff['realName']);
                                    echo $option;
                                }
                                ?>
                            </select>
                        </div>
                    </div>

                    <div class="control-group" op="editFiled">
                        <label class="control-label"
                               for="edit_delay"><?php echo Enum_Lang::getPageText('service', 'delay'); ?>
                            ：</label>
                        <div class="controls">
                            <input id="edit_delay" data-paramkey='date' type="text" class="form-control input-medium"
                                   value=''/>
                        </div>
                    </div>


                    <div class="control-group" op="editFiled">
                        <label class="control-label"
                               for="edit_status"><?php echo Enum_Lang::getPageText('service', 'status'); ?>：</label>
                        <div class="controls">
                            <select id="edit_status"
                                    data-title="<?php echo Enum_Lang::getPageText('service', 'status'); ?>">
                                <?php
                                foreach ($statusList as $value => $name) {
                                    $option = sprintf("<option value=\"%s\">%s</option>", $value, $name);
                                    echo $option;
                                }
                                ?>
                            </select>


                        </div>
                    </div>

                    <div class="control-group" op="editFiled">
                        <label class="control-label"
                               for="edit_memo"><?php echo Enum_Lang::getPageText('service', 'memo'); ?>：</label>
                        <div class="controls">
                            <textarea id="edit_memo" class="span4" rows="5"
                                      data-title="<?php echo Enum_Lang::getPageText('service', 'memo'); ?>"></textarea>
                        </div>
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" id="saveTaskOrderData"
                        data-loading-text="<?php echo Enum_Lang::getPageText('system', 'saveing'); ?>"><?php echo Enum_Lang::getPageText('system', 'save'); ?></button>
                <button type="button" class="btn btn-primary" data-dismiss="modal"
                        id='closeEditor'><?php echo Enum_Lang::getPageText('system', 'close'); ?></button>
            </div>
        </div>
    </div>
</div>
