<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/select2.min.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/video.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/datetimepicker.css"/>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('nav', 'taskOrderMgmt'); ?>
                        <button id="createData" class="btn btn-info" style="margin-left: 5px;" type="button"
                                data-toggle="modal"
                                data-target="#editor"><?php echo Enum_Lang::getPageText('system', 'create'); ?>
                        </button>
                    </h1>
                </div>
                <?php include($webConfig['layoutPath'] . '/service/task_order_filter.phtml') ?>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th><?php echo Enum_Lang::getPageText('service', 'roomNo'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('service', 'taskName'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('service', 'count'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('service', 'taskPic'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('service', 'createTime'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('service', 'updateTime'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('service', 'memo'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('service', 'staff'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('service', 'status'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('system', 'option'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="dataList"></tbody>
                                </table>
                            </div>
                            <div id="pageDiv" style='padding: 20px;'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include($webConfig['layoutPath'] . '/service/task_order_edit.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/service/task_order_process_edit.phtml'); ?>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        checkParams: '<?php echo json_encode(Enum_Activity::getActivityMustInput());?>',
        checkProcessParams: '<?php echo json_encode(Enum_Service::getTaskProcessMustInput()); ?>',
        listUrl: '/serviceajax/getTaskOrderList',
        createUrl: '/serviceajax/createTaskOrder',
        updateUrl: '/serviceajax/updateTaskOrder',
    };
</script>
<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_form.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/select2.full.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/zh-CN.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/bootstrap-datetimepicker.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/bootstrap-datetimepicker.zh-CN.js"
        type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/datatimepicker.config.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/service/task_order.js"></script>
</body>
</html>
<script id="dataList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td type="id" data-value="{{info.id}}">{{info.id}}</td>
        <td type="roomNo" data-value="{{info.roomNo}}">{{info.room_no}}</td>
        <td type="taskTitleLang1" data-value="{{info.taskTitleLang1}}">{{info.taskTitleLang1}}</td>
        <td type="count" data-value="{{info.count}}">{{info.count}}</td>
        <td type="pic" data-value="{{info.pic}}">
            {{if info.pic}}
            <a href="{{info.pic}}" target="_blank">
                <img src="{{info.pic}}" style="max-width: 100px;max-height: 100px;"/>
            </a>
            {{/if}}
        </td>
        <td type="createdAt" data-value="{{info.created_at}}">{{info.created_at}}</td>
        <td type="updatedAt" data-value="{{info.updated_at}}">{{info.updated_at}}</td>
        <td type="delay" data-value="{{info.delay}}" style="display: none">{{info.delay}}</td>
        <td type="memo" data-value="{{info.memo}}">{{info.memo}}</td>
        <td type="adminid" data-value="{{info.admin_id}}">{{info.admin_name}}</td>
        <td type="status" data-value="{{info.status}}">{{info.statusShow}}</td>

        <td>
            <button op="editTaskProcess" type="button" class="btn btn-info btn-sm"
                    data-dataid="{{info.id}}"><?php echo Enum_Lang::getPageText('service', 'TaskOrderProcess'); ?></button>
        </td>
    </tr>
    {{/each}}
</script>
