<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/select2.min.css"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/video.css"/>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        <?php echo Enum_Lang::getPageText('nav', 'taskMgmt'); ?>
                        <button id="createData" class="btn btn-info" style="margin-left: 5px;" type="button"
                                data-toggle="modal"
                                data-target="#editor"><?php echo Enum_Lang::getPageText('system', 'create'); ?>
                        </button>
                    </h1>
                </div>
                <?php include($webConfig['layoutPath'] . '/service/task_filter.phtml') ?>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th><?php echo Enum_Lang::getPageText('service', 'taskName'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('service', 'price'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('service', 'taskCategory'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('service', 'taskPic'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('service', 'status'); ?></th>
                                        <th><?php echo Enum_Lang::getPageText('system', 'option'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody id="dataList"></tbody>
                                </table>
                            </div>
                            <div id="pageDiv" style='padding: 20px;'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include($webConfig['layoutPath'] . '/service/task_edit.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/service/task_process_edit.phtml'); ?>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        checkParams: '<?php echo json_encode(Enum_Activity::getActivityMustInput());?>',
        checkProcessParams: '<?php echo json_encode(Enum_Service::getTaskProcessMustInput()); ?>',
        listUrl: '/serviceajax/getTaskList',
        createUrl: '/serviceajax/createTask',
        updateUrl: '/serviceajax/updateTask',
        updateProcessUrl: '/serviceajax/updateTaskProcess',
    };
</script>
<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_form.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/select2.full.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/zh-CN.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/plupload/js/plupload.full.min.js"
        type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/service/task.js"></script>
</body>
</html>
<script id="dataList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td type="id" data-value="{{info.id}}">{{info.id}}</td>
        <td type="titleLang1" data-value="{{info.titleLang1}}">{{info.titleLang1}}</td>
        <td type="price" data-value="{{info.price}}">{{info.price}}</td>
        <td type="categoryid" data-value="{{info.category_id}}">{{info.category_title1}}</td>
        <td type="pic" data-value="{{info.pic}}">
            {{if info.pic}}
            <a href="{{info.pic}}" target="_blank">
                <img src="{{info.pic}}" style="max-width: 100px;max-height: 100px;"/>
            </a>
            {{/if}}
        </td>
        <td type="status" data-value="{{info.status}}">{{info.statusShow}}</td>
        <td type="titleLang2" data-value="{{info.titleLang2}}" style="display:none;"></td>

        <td type="departmentid" data-value="{{info.process_info.department_id}}" style="display:none;"></td>
        <td type="staffid" data-value="{{info.process_info.staff_id}}" style="display:none;"></td>
        <td type="highlevel" data-value="{{info.process_info.highest_level}}" style="display:none;"></td>
        <td type="levelinterval1" data-value="{{info.process_info.level_interval_1}}" style="display:none;"></td>
        <td type="levelinterval2" data-value="{{info.process_info.level_interval_2}}" style="display:none;"></td>
        <td type="levelinterval3" data-value="{{info.process_info.level_interval_3}}" style="display:none;"></td>
        <td type="levelinterval4" data-value="{{info.process_info.level_interval_4}}" style="display:none;"></td>
        <td type="levelinterval5" data-value="{{info.process_info.level_interval_5}}" style="display:none;"></td>
        <td type="sms" data-value="{{info.process_info.sms}}" style="display:none;"></td>
        <td type="email" data-value="{{info.process_info.email}}" style="display:none;"></td>

        <td>
            <button op="editDataOne" type="button" class="btn btn-info btn-sm"
                    data-dataid="{{info.id}}"><?php echo Enum_Lang::getPageText('system', 'edit'); ?></button>
            <button op="editTaskProcess" type="button" class="btn btn-info btn-sm"
                    data-dataid="{{info.id}}"><?php echo Enum_Lang::getPageText('service', 'editTaskProcess'); ?></button>

        </td>
    </tr>
    {{/each}}
</script>
