<div class="modal hide fade yulong" id="staffListEditor" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true" mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"><?php echo Enum_Lang::getPageText('nav', 'appStaff'); ?></h4>
            </div>
            <div class="modal-body" id="detailBodyt" mf="modalfix">
                <form class="form-horizontal" id="staffEditorList">
                    <table>
                        <tr><td></td><td>周一</td><td>周二</td><td>周三</td><td>周四</td><td>周五</td><td>周六</td><td>周日</td></tr>
                        <?php
                            for($hour = 0; $hour<24; $hour++){
                                $output = sprintf("
                        <tr>
                            <td>%1\$02d:00-%1\$02d:59</td>
                            <td><input op=\"edit_staffList\" type=\"checkbox\" name=\"1%1$02d\" value=\"1%1$02d\"></td>
                            <td><input op=\"edit_staffList\" type=\"checkbox\" name=\"2%1$02d\" value=\"2%1$02d\"></td>
                            <td><input op=\"edit_staffList\" type=\"checkbox\" name=\"3%1$02d\" value=\"3%1$02d\"></td>
                            <td><input op=\"edit_staffList\" type=\"checkbox\" name=\"4%1$02d\" value=\"4%1$02d\"></td>
                            <td><input op=\"edit_staffList\" type=\"checkbox\" name=\"5%1$02d\" value=\"5%1$02d\"></td>
                            <td><input op=\"edit_staffList\" type=\"checkbox\" name=\"6%1$02d\" value=\"6%1$02d\"></td>
                            <td><input op=\"edit_staffList\" type=\"checkbox\" name=\"7%1$02d\" value=\"7%1$02d\"></td>
                        </tr>
                                ", $hour);
                                echo $output;
                            }

                        ?>
                    </table>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" id="saveStaffList" data-loading-text="保存中...">保存
                </button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" id='closeEditor'>关闭</button>
            </div>
        </div>
    </div>
</div>
