<div class="hero-unit hero-unit-custom hero-unit-mgdbtm clearfix" id="listFilter">
    <form class="form-horizontal">
        <div class="control-group control-group-block">
            <div class="pull-left control-item">
                <span class="control-label">ID：</span>
                <div class="controls">
                    <input id="userid" data-paramkey='id' type="number" class="form-control input-medium" op="filterCase" value=''/>
                </div>
            </div>
            <div class="pull-left control-item">
                <span class="control-label"><?php echo Enum_Lang::getPageText('shopping', 'shoppingTitle'); ?>：</span>
                <div class="controls">
                    <input id="filter_title" data-paramkey='title' type="text" class="form-control input-medium" op="filterCase"/>
                </div>
            </div>
            <div class="pull-left control-item">
                <span class="control-label"><?php echo Enum_Lang::getPageText('shopping', 'tagTitle'); ?>：</span>
                <div class="controls">
                    <select id="filter_tagid" data-title="标签" data-paramkey='tag' class="input-medium select-long" op="filterCase">
                        <option value="all"><?php echo Enum_Lang::getPageText('system', 'all'); ?></option>
                        <?php
                        foreach ($tagList as $tag) {
                            $output = "";
                            $language = Enum_Lang::getSystemLang(true);
                            if (empty($tag['children'])) {
                                $output = sprintf("<option value='%s'>%s</option>", $tag['id'], $tag['title_lang' . $language]);
                            } else {
                                $output = sprintf("<option value='%s'>%s(一级标签)</option>", $tag['id'], $tag['title_lang' . $language]);
                                foreach ($tag['children'] as $child) {
                                    $option = sprintf("<option value='%s'>%s</option>", $child['id'], $child['title_lang' . $language]);
                                    $output .= $option;
                                }
                                $output = sprintf('<optgroup label="%s">%s</optgroup>', $tag['title_lang' . $language], $output);
                            }
                            echo $output;
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="pull-left control-item">
                <span class="control-label"><?php echo Enum_Lang::getPageText('shopping', 'status'); ?>：</span>
                <div class="controls">
                    <select id="filter_status" data-paramkey='status' class="input-medium select-long" op="filterCase">
                        <option value="all"><?php echo Enum_Lang::getPageText('system', 'all'); ?></option>
                        <option value="0"><?php echo Enum_Lang::getPageText('shopping', 'disable'); ?></option>
                        <option value="1"><?php echo Enum_Lang::getPageText('shopping', 'enable'); ?></option>
                    </select>
                </div>
            </div>
            <button id="searchBtn" class="mgtop5 pull-left btn btn-primary" type="button"
                    data-loading-text="<?php echo Enum_Lang::getPageText('system', 'searching'); ?>">
                <?php echo Enum_Lang::getPageText('system', 'search'); ?>
            </button>
        </div>
    </form>
</div>
