<div class="hero-unit hero-unit-custom hero-unit-mgdbtm clearfix" id="listFilter">
    <form class="form-horizontal">
        <div class="control-group control-group-block">

            <div class="pull-left control-item">
                <span class="control-label"><?php echo Enum_Lang::getPageText('activity', 'activity'); ?>：</span>
                <div class="controls">
                    <select id="filter_activityid" data-paramkey='activityid' class="input-medium select-long" op="filterCase">
                        <option value="all"><?php echo Enum_Lang::getPageText('system', 'all'); ?></option>
                        <?php foreach ($activityList as $activity) { ?>
                            <option value="<?php echo $activity['id']; ?>"><?php echo $activity['title_lang1']; ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>

            <div class="pull-left control-item">
                <span class="control-label"><?php echo Enum_Lang::getPageText('activity', 'status'); ?>：</span>
                <div class="controls">
                    <select id="filter_status" data-paramkey='status' class="input-medium select-long" op="filterCase">
                        <option value="all"><?php echo Enum_Lang::getPageText('system', 'all'); ?></option>
                        <option value="0"><?php echo Enum_Lang::getPageText('activity', 'disable'); ?></option>
                        <option value="1"><?php echo Enum_Lang::getPageText('activity', 'enable'); ?></option>
                    </select>
                </div>
            </div>

            <button id="searchBtn" class="mgtop5 pull-left btn btn-primary" type="button" data-loading-text="<?php echo Enum_Lang::getPageText('system', 'searching'); ?>">
                <?php echo Enum_Lang::getPageText('system', 'search'); ?>
            </button>
        </div>
    </form>
</div>
