<div class="modal hide fade yulong" id="editor" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"><?php echo Enum_Lang::getPageText('group', 'editTitle'); ?></h4>
            </div>
            <div class="modal-body" id="detailBody" mf="modalfix">
                <form class="form-horizontal" id="listEditor">
                    <input type="hidden" id="edit_id" value="0">

                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_activityid"><?php echo Enum_Lang::getPageText('activity', 'activity'); ?>：</label>
                        <div class="controls">
                            <select id="edit_activityid" data-title="活动">
                                <option value=""><?php echo Enum_Lang::getPageText('system', 'all'); ?></option>
                                <?php foreach ($activityList as $activity) { ?>
                                    <option value="<?php echo $activity['id']; ?>"><?php echo $activity['title_lang1']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>

                    <div class="control-group" op="editFiled">
                        <?php $filedName = 'pic';
                        $filedTitle = Enum_Lang::getPageText('activity', 'pic'); ?>
                        <label class="control-label" for="edit_<?php echo $filedName; ?>"><?php echo $filedTitle; ?>：</label>
                        <div class="controls">
                            <img src="" id="edit_<?php echo $filedName; ?>_show" style="max-height: 80px;"/>
                            <input type="file" id="edit_<?php echo $filedName; ?>" placeholder="<?php echo $filedTitle; ?>" class="span4" data-title="楼层图" accept="<?php echo implode(",", $allowTypeImage); ?>">
                            <img src="<?php echo $webConfig['imgDomain'];?>/img/icons/cross.png" class="deleteFile" data-for="edit_<?php echo $filedName; ?>" data-show="edit_<?php echo $filedName; ?>_show">
                        </div>
                    </div>


                    <div class="control-group" op="editFiled">
                        <?php $filedName = 'sort';
                        $filedTitle = Enum_Lang::getPageText('activity', 'sort'); ?>
                        <label class="control-label" for="edit_<?php echo $filedName; ?>"><?php echo $filedTitle; ?>：</label>
                        <div class="controls">
                            <input type="number" id="edit_<?php echo $filedName; ?>" placeholder="<?php echo $filedTitle; ?>" class="span1" data-title="<?php echo $filedTitle; ?>">
                        </div>
                    </div>


                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_status"><?php echo Enum_Lang::getPageText('activity', 'status'); ?>：</label>
                        <div class="controls">
                            <select id="edit_status" data-title="状态">
                                <option value="1"><?php echo Enum_Lang::getPageText('activity', 'enable'); ?></option>
                                <option value="0"><?php echo Enum_Lang::getPageText('activity', 'disable'); ?></option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" id="saveListData"
                        data-loading-text="<?php echo Enum_Lang::getPageText('system', 'saveing'); ?>"><?php echo Enum_Lang::getPageText('system', 'save'); ?></button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" id='closeEditor'><?php echo Enum_Lang::getPageText('system', 'close'); ?></button>
            </div>
        </div>
    </div>
</div>
